### PR TITLE
Minify JS and CSS, compress images

### PR DESCRIPTION
**Pull request by fennadew**
Minify JS and CSS and compress images. This will make the website faster without changing any code.

### CODE REVIEW

**Comment by wooorm** [comment]
@fennadew Hey your points didn’t come through correctly, I was able to add the async javascript points, but not the other ones. Could you try again?

**Comment by wooorm** [comment]
Related to GH-46.
Related to GH-67.

**Comment by fennadew** [comment]
How?

**Comment by wooorm** [comment]
By creating new PRs!
Maybe this is helpful? https://guides.github.com/introduction/flow/

**Pull request merged**
