### PR TITLE
Added tips for blocking javascript

### PR DESCRIPTION
**Pull request by Alexvanderwal**
https://gtmetrix.com/reports/www.cmd-amsterdam.nl/Va2KDvHk

Gave insights on how to reduce the render blocking caused by specific javascript files.

### CODE REVIEW

**Comment by wooorm** [comment]
@Cascuna Hey could you group this into one topic?

**Comment by Alexvanderwal** [comment]
@wooorm Done :+1:

**Comment by wooorm** [comment]
See the other PR ;)

**Comment by Alexvanderwal** [comment]
Corrected it with a hopefully valuable tip.

**Pull request merged**
