### PR TITLE
Blocking css

### PR DESCRIPTION
**Pull request by Alexvanderwal**
Added tips to get rid of the blocking css.

### CODE REVIEW

**Comment by wooorm** [comment]
Could you rewrite this into one tip?

**Comment by Alexvanderwal** [comment]
@wooorm My bad! should be alright now

**Comment by wooorm** [comment]
😱

screen shot 2018-03-13 at 18 39 54

What I meant was, more like all the points in the current readme: generic enough that it works for other sites as well? What’s the thing to check? ;)

**Comment by Alexvanderwal** [comment]
Ah.. My bad. Didn't read the other addition to the Readme. Updated my question to be more 'tip' like, however, this one is already in the document. Should i supplement it for something else?

**Comment by wooorm** [comment]
Sweet!

**Pull request merged**
